# frozen_string_literal: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

# Spec files are expected to be long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

# Allow longer methods in core implementation
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

# Allow higher complexity for core aggregation logic
Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ModuleLength:
  Max: 150

# Allow keyword arguments for clarity in internal methods
Metrics/ParameterLists:
  CountKeywordArgs: false

# Documentation not required for reopened classes
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/activerecord/eager/aggregation.rb'
